Update master annotation file
d3b-center/hope-cohort-analysis pull request #109
Opened 2024-06-21 13:17 UTC by komalsrathi

Update master annotation file for downstream analyses and for manuscript.

2024-06-21 13:33 UTC, komalsrathi commented
Requires TMB calculation to be run first, so converting this to draft for now.

2024-07-13 17:48 UTC, jharenza requested changes
hey @komalsrathi I made some comments about subtypes that probably should not be changing TP53 status based on last release results. Can you have a look? Also, can you stack your PRs on the right base branch - this is showing 41 changes bc it is on master, but should be stacked on some other branch. You can just edit the title and change the base branch, thanks!

2024-07-13 17:48 UTC, jharenza commented on analyses/master_annotation/results/master_annotation.tsv
> +7316-2241	Methylation, Phospho-Proteomics, RNA-Seq, WGS_tumor_only, Whole Cell Proteomics	Treatment naive	Glioblastoma (WHO grade IV)	Initial CNS Tumor	Cortical	Hemispheric	Female	2373	[0,15]	HGG, H3
is loss of TP53 expected in the subtype here?

2024-07-13 17:48 UTC, jharenza commented on analyses/master_annotation/results/master_annotation.tsv
> +7316-2594	Phospho-Proteomics, RNA-Seq, WGS, Whole Cell Proteomics	Treatment naive	Astrocytoma (WHO grade III/IV)	Initial CNS Tumor	Midline	Midline	Male	2869	[0,15]	DMG, H3 K28	(DMG) Diffuse Midline G
similarly here

2024-07-13 17:48 UTC, jharenza commented on analyses/tp53_nf1_score/results/TP53_NF1_snv_alteration.tsv
> +NA	NA	NA	NA	NA	BS_3NX3RBCX	No_TP53_NF1_alt
seems like this sample should have a TP53 deletion per the last release.

2024-07-13 17:48 UTC, jharenza commented on analyses/tp53_nf1_score/results/TP53_NF1_snv_alteration.tsv
> +NA	NA	NA	NA	NA	BS_WJB33V17	No_TP53_NF1_alt
think we need to check each of these which are different from last release

2024-07-15 13:25 UTC, komalsrathi commented
> hey @komalsrathi I made some comments about subtypes that probably should not be changing TP53 status based on last release results. Can you have a look? Also, can you stack your PRs on the right base branch - this is showing 41 changes bc it is on master, but should be stacked on some other branch. You can just edit the title and change the base branch, thanks!

I don't understand. I created this PR after these PRs:

1) merge files 
2) NF1 score model 
3) HGG subtyping 
4) TMB calculation

And each PR was created off of the previous PR. Screenshots below that the previous commits were incorporated in this PR:

<img width="923" alt="Screenshot 2024-07-15 at 9 24 46 AM" src="https://github.com/user-attachments/assets/abedb3f3-2ccd-4982-b03c-7974acd09266">

<img width="905" alt="Screenshot 2024-07-15 at 9 24 57 AM" src="https://github.com/user-attachments/assets/fe267acf-927f-4983-8a53-291334fa3741">

2024-10-28 16:53 UTC, merged