Add master annotation
d3b-center/hope-cohort-analysis pull request #98
Opened 2024-03-01 06:12 UTC by komalsrathi

Per slack conversation with @mkoptyra, he has requested for a combined annotation file that has information used by availability plots and Oncoplots.

2024-03-19 15:32 UTC, komalsrathi commented
@jharenza any chance of reviewing and getting this merged this week? Thank you!

2024-03-25 17:42 UTC, jharenza requested changes
The directory for TMB needs to be updated here, as it is searching within the annotation dir, so I made those suggestions. Following those, this runs and reproduces. 

Also, suggest to add the instruction `Rscript --vanilla 01-master_annotation.R` to the readme or add a run script.

2024-03-25 17:42 UTC, jharenza commented on analyses/master_annotation/01-master_annotation.R
> +output_dir <- file.path(analyses_dir, "results")
```suggestion
tmb_dir <- file.path(root_dir, "analyses", "tmb-calculation")
output_dir <- file.path(analyses_dir, "results")
```

2024-03-25 17:42 UTC, jharenza commented on analyses/master_annotation/01-master_annotation.R
> +tmb_paired_output <- read_tsv("analyses/tmb-calculation/results/wgs_paired/snv-mutation-tmb-coding.tsv") %>%
```suggestion
tmb_paired_output <- read_tsv(file.path(tmb_dir, "results/wgs_paired/snv-mutation-tmb-coding.tsv")) %>%
```

2024-03-25 17:42 UTC, jharenza commented on analyses/master_annotation/01-master_annotation.R
> +tmb_tumor_only_output <- read_tsv("analyses/tmb-calculation/results/wgs_tumor_only/snv-mutation-tmb-coding.tsv") %>%
```suggestion
tmb_tumor_only_output <- read_tsv(file.path(tmb_dir, "results/wgs_tumor_only/snv-mutation-tmb-coding.tsv")) %>%
```

2024-03-25 18:16 UTC, jharenza approved these changes

2024-03-25 18:24 UTC, merged